[project]
name = "personal-website"
version = "0.1.0"
description = "Matthias Schoettle's personal website"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs-material==9.5.36",
]

[tool.uv]
dev-dependencies = [
    "pre-commit==3.8.0",
]
