name: Deployment

concurrency:
  group: staging
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Deploy
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        shell: bash
        run: |
          echo "Launching SSH agent..."
          eval "$(ssh-agent -s)"
          echo "Adding private key..."
          ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 --decode)
          echo "Connecting via SSH and executing commands"
          ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" docker ps
