name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4.1.7
      - name: Install uv
        uses: astral-sh/setup-uv@v3.0.0
        id: setup-uv
        with:
          version: "0.4.10"
          enable-cache: true
      - name: Print the installed version
        run: echo "Installed uv version is ${{ steps.setup-uv.outputs.uv-version }}"
      - name: Install Python
        run: uv python install
      # - name: Run pre-commit
      #   run: uv run pre-commit run --all-files
      - name: Print python version
        run: uv python list && which python
      # - uses: actions/cache@v4
        # with:
          # path: ~/.cache/pre-commit
          # key: pre-commit-3|${{ hashFiles('.pre-commit-config.yaml') }}
      # - name: Run pre-commit
        # run: uv run pre-commit run --show-diff-on-failure --color=always --all-files
        # shell: bash
      - uses: pre-commit/action@v3.0.1
