name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4.1.7
      - name: Install uv
        uses: astral-sh/setup-uv@v3.1.1
        id: setup-uv
        with:
          # TODO: figure out a way to have this updated by Renovate
          version: "0.4.10"
          enable-cache: true
      - name: Print the installed version
        run: echo "Installed uv version is ${{ steps.setup-uv.outputs.uv-version }}"
      - name: Install Python
        run: uv python install
      - name: Print python version
        run: uv python list
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
