name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4.1.7
      - name: Install uv
        uses: astral-sh/setup-uv@v3.0.0
        with:
          version: "0.4.10"
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
