name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4.1.7
      - name: Install Python
        uses: actions/setup-python@v5.2.0
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
